/* @flow */
window.gcexports.globalLexicon = {
  "table" : { "tk": 1, "name": "TABLE", "cls": "function", "length": 1, "arity": 1 },
  "thead" : { "tk": 1, "name": "THEAD", "cls": "function", "length": 1, "arity": 1 },
  "tbody" : { "tk": 1, "name": "TBODY", "cls": "function", "length": 1, "arity": 1 },
  "th" : { "tk": 1, "name": "TH", "cls": "function", "length": 1, "arity": 1 },
  "tr" : { "tk": 1, "name": "TR", "cls": "function", "length": 1, "arity": 1 },
  "td" : { "tk": 1, "name": "TD", "cls": "function", "length": 1, "arity": 1 },
  "logo-width" : { "tk": 1, "name": "LOGO-WIDTH", "cls": "function", "length": 2 },
  "width" : { "tk": 1, "name": "WIDTH", "cls": "function", "length": 2 },
  "height" : { "tk": 1, "name": "HEIGHT", "cls": "function", "length": 2 },
  "stack" : { "tk": 1, "name": "STACK-CHART", "cls": "function", "length": 0, "arity": 0 },
  "treemap" : { "tk": 1, "name": "TREEMAP-CHART", "cls": "function", "length": 0, "arity": 0 },
  "pack" : { "tk": 1, "name": "PACK-CHART", "cls": "function", "length": 1, "arity": 1 },
  "bar" : { "tk": 1, "name": "BAR-CHART", "cls": "function", "length": 2, "arity": 2 },
  "val" : { "tk": 1, "name": "VAL", "cls": "function", "length": 2 , "arity": 2 },
  "key" : { "tk": 1, "name": "KEY", "cls": "function", "length": 2 , "arity": 2 },
  "len" : { "tk": 1, "name": "LEN", "cls": "function", "length": 1 , "arity": 1 },
  "concat" : { "tk": 1, "name": "CONCAT", "cls": "function", "length": 1 , "arity": 1 },
  "add" : { "tk": 1, "name": "ADD", "cls": "function", "length": 2 , "arity": 2 },
  "mul" : { "tk": 1, "name": "MUL", "cls": "function", "length": 2 , "arity": 2 },
  "style" : { "tk": 1, "name": "STYLE", "cls": "function", "length": 2, "arity": 2 },
  "map" : { "tk": 1, "name": "MAP", "cls": "function", "length": 2, "arity": 2 },
  "apply" : { "tk": 1, "name": "APPLY", "cls": "function", "length": 2, "arity": 2 },
  "in" : { "tk": 1, "name": "IN", "cls": "function", "length": 1, "arity": 1 },
  "arg" : { "tk": 1, "name": "ARG", "cls": "function", "length": 1, "arity": 1 }
}
